pipeline:
  name: enterprise-cicd
  identifier: enterprise_cicd
  projectIdentifier: harnessci
  orgIdentifier: default

  stages:

  # =========================
  # 1. CI BUILD STAGE
  # =========================
    - stage:
        name: Build_and_Test
        identifier: build_test
        type: CI
        spec:
          infrastructure:
            type: Cloud
            spec: {}

          execution:
            steps:

              # Clone Code
              - step:
                  type: GitClone
                  name: Clone
                  identifier: clone_code
                  spec:
                    connectorRef: Github
                    repoName: maven-simple
                    build:
                      type: branch
                      spec:
                        branch: main

              # Build (Java)
              - step:
                  type: Run
                  name: Maven Build
                  identifier: maven_build
                  spec:
                    image: maven:3.9.6-eclipse-temurin-17
                    shell: Sh
                    command: mvn clean install

              # Unit Tests
              - step:
                  type: Run
                  name: Run Tests
                  identifier: run_tests
                  spec:
                    image: maven:3.9.6-eclipse-temurin-17
                    shell: Sh
                    command: mvn test

              # Build Docker Image
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build_and_Push
                  identifier: build_push
                  spec:
                    connectorRef: dockerhub_conn
                    repo: enterprise/app
                    tags:
                      - <+pipeline.sequenceId>

              # Security Scan
              - step:
                  type: Run
                  name: Security Scan
                  identifier: security_scan
                  spec:
                    image: aquasec/trivy
                    shell: Sh
                    command: |
                      trivy image enterprise/app:<+pipeline.sequenceId> 
